# Generated by Django 2.0.1 on 2018-02-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=120)),
                ('team_location_name', models.CharField(max_length=120)),
                ('team_metro', models.CharField(max_length=120)),
            ],
        ),
    ]
