# Generated by Django 2.0.1 on 2018-02-18 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(default=None)),
                ('event_time', models.TimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fs.Event')),
            ],
        ),
        migrations.CreateModel(
            name='FanGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=120)),
                ('official', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(max_length=120)),
                ('abbreviation', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_name', models.CharField(default=None, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=120)),
                ('team_location_name', models.CharField(max_length=120)),
                ('team_metro', models.CharField(max_length=120)),
                ('fan_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fs.FanGroup')),
                ('team_league', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fs.League')),
                ('team_sport', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fs.Sport')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password_hash', models.CharField(default=None, max_length=128)),
                ('confirmed', models.BooleanField(default=0)),
                ('user_type', models.CharField(default=None, max_length=32)),
                ('name', models.CharField(max_length=70)),
                ('user_location', models.CharField(max_length=32)),
                ('street_address', models.CharField(max_length=95)),
                ('city', models.CharField(max_length=35)),
                ('state', models.CharField(max_length=20)),
                ('zip_code', models.CharField(max_length=5)),
                ('phone_num', models.PositiveIntegerField(default=None)),
                ('member_since', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='sport',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fs.Sport'),
        ),
        migrations.AddField(
            model_name='favoriteteam',
            name='fav_team',
            field=models.ManyToManyField(to='fs.Team'),
        ),
        migrations.AddField(
            model_name='favoriteteam',
            name='user_id',
            field=models.ManyToManyField(to='fs.User'),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='user',
            field=models.ManyToManyField(to='fs.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='bar',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bar', to='fs.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='fan_team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fs.Team'),
        ),
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fs.FanGroup'),
        ),
        migrations.AddField(
            model_name='event',
            name='opp_team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fs.Team'),
        ),
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fs.User'),
        ),
    ]
