# Generated by Django 2.0.1 on 2018-02-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_num',
            field=models.PositiveIntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='street_address',
            field=models.CharField(blank=True, max_length=95),
        ),
        migrations.AlterField(
            model_name='user',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
