# Generated by Django 2.0.1 on 2018-02-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0002_auto_20180207_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Fan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=70)),
                ('location', models.CharField(max_length=32)),
            ],
        ),
    ]
