# Generated by Django 2.0.1 on 2018-02-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0003_user_fan'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=70)),
                ('street_address', models.CharField(max_length=95)),
                ('city', models.CharField(max_length=35)),
            ],
        ),
    ]
