# Generated by Django 2.0.1 on 2018-02-08 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0004_user_bar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='leagues',
            name='sport',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fs.Sports'),
        ),
    ]
