# Generated by Django 2.0.1 on 2018-02-08 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0005_auto_20180208_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sports',
            name='sport_name',
            field=models.CharField(choices=[('BB', 'Basketball'), ('BS', 'Baseball'), ('FB', 'Football'), ('HY', 'Hockey'), ('SC', 'Soccer')], default=None, max_length=2),
        ),
    ]
