# Generated by Django 2.0.1 on 2018-02-08 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0006_auto_20180208_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='team_sport',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fs.Sports'),
        ),
    ]
