# Generated by Django 2.0.1 on 2018-02-20 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0007_auto_20180220_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='fan_group',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='fs.FanGroup'),
        ),
    ]
