# Generated by Django 2.0.1 on 2018-02-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0007_teams_team_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fan_Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=120)),
            ],
        ),
    ]
