# Generated by Django 2.0.1 on 2018-02-20 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0008_auto_20180220_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='fan_group',
        ),
    ]
