# Generated by Django 2.0.1 on 2018-02-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0008_fan_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='fan_groups',
            name='official',
            field=models.BooleanField(default=0),
        ),
    ]
