# Generated by Django 2.0.1 on 2018-02-08 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0009_fan_groups_official'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fs.User_Bar')),
                ('group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fs.Fan_Groups')),
            ],
        ),
    ]
