# Generated by Django 2.0.1 on 2018-02-20 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0010_remove_event_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattendance',
            name='fan_group',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='fs.FanGroup'),
        ),
    ]
