# Generated by Django 2.0.1 on 2018-02-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0010_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_bar',
            name='phone_num',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='user_bar',
            name='state',
            field=models.CharField(default=None, max_length=2),
        ),
        migrations.AddField(
            model_name='user_bar',
            name='zip_code',
            field=models.CharField(default=None, max_length=5),
        ),
    ]
