# Generated by Django 2.0.1 on 2018-02-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0011_auto_20180208_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(choices=[('UC', 'User Created'), ('BC', 'Bar Created'), ('GS', 'Group Sponsored')], default='UC', max_length=2)),
            ],
        ),
    ]
