# Generated by Django 2.0.1 on 2018-02-25 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0011_eventattendance_fan_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteteam',
            name='user_id',
        ),
        migrations.AddField(
            model_name='favoriteteam',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fs.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_team',
            field=models.ManyToManyField(blank=True, related_name='favorite_users', through='fs.FavoriteTeam', to='fs.Team'),
        ),
        migrations.RemoveField(
            model_name='favoriteteam',
            name='fav_team',
        ),
        migrations.AddField(
            model_name='favoriteteam',
            name='fav_team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fs.Team'),
            preserve_default=False,
        ),
    ]
