# Generated by Django 2.0.1 on 2018-02-25 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0012_auto_20180225_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='favorite_team',
            new_name='favorite_teams',
        ),
    ]
