# Generated by Django 2.0.1 on 2018-02-08 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0012_bar_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(choices=[('OG', 'Organizer'), ('AT', 'Attendee')], default='OG', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fs.Events')),
                ('user_role', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fs.Attendee_Role')),
            ],
        ),
    ]
