# Generated by Django 2.0.1 on 2018-02-10 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0013_attendee_role_event_attendence'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_fan',
            name='fav_nba',
            field=models.ForeignKey(default=None, limit_choices_to={'team_league': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fs.Teams'),
        ),
    ]
