# Generated by Django 2.0.1 on 2018-02-11 20:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0014_user_fan_fav_nba'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_fan',
            name='member_since',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
