# Generated by Django 2.0.1 on 2018-03-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0015_auto_20180307_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_teams',
            field=models.ManyToManyField(blank=True, related_name='favorite_users', to='fs.Team'),
        ),
    ]
