# Generated by Django 2.0.1 on 2018-03-24 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0016_user_favorite_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='team_league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fs.League'),
        ),
    ]
