# Generated by Django 2.0.1 on 2018-02-11 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0016_user_bar_member_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_bar',
            name='nba_affiliation',
            field=models.ForeignKey(default=None, limit_choices_to={'team_league': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fs.Teams'),
        ),
    ]
