# Generated by Django 2.0.1 on 2018-02-11 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0017_user_bar_nba_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_bar',
            name='epl_affiliation',
            field=models.ForeignKey(default=None, limit_choices_to={'team_league': 5}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fs.Teams'),
        ),
        migrations.AddField(
            model_name='user_bar',
            name='mlb_affiliation',
            field=models.ForeignKey(default=None, limit_choices_to={'team_league': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fs.Teams'),
        ),
        migrations.AddField(
            model_name='user_bar',
            name='mls_affiliation',
            field=models.ForeignKey(default=None, limit_choices_to={'team_league': 6}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fs.Teams'),
        ),
        migrations.AddField(
            model_name='user_bar',
            name='nfl_affiliation',
            field=models.ForeignKey(default=None, limit_choices_to={'team_league': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fs.Teams'),
        ),
        migrations.AddField(
            model_name='user_bar',
            name='nhl_affiliation',
            field=models.ForeignKey(default=None, limit_choices_to={'team_league': 4}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fs.Teams'),
        ),
    ]
