# Generated by Django 2.0.1 on 2018-03-24 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0017_event_team_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='team_league',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fs.League'),
        ),
    ]
