# Generated by Django 2.0.1 on 2018-02-11 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0018_auto_20180211_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_fan',
            name='fav_mlb',
            field=models.ForeignKey(default=None, limit_choices_to={'team_league': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fs.Teams'),
        ),
    ]
