# Generated by Django 2.0.1 on 2018-03-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0019_auto_20180324_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_hash',
        ),
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
