# Generated by Django 2.0.1 on 2018-03-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0021_auto_20180324_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default=None, max_length=70),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_location',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
