# Generated by Django 2.0.1 on 2018-02-11 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0021_user_fan_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='fan_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fs.Fan_Groups'),
        ),
    ]
