# Generated by Django 2.0.1 on 2018-03-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0022_auto_20180324_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, default=None, max_length=32),
        ),
    ]
