# Generated by Django 2.0.1 on 2018-02-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0023_user_fan_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_bar',
            name='password_hash',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
