# Generated by Django 2.0.1 on 2018-02-11 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0024_user_bar_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='fan_team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fs.Teams'),
        ),
        migrations.AddField(
            model_name='events',
            name='opp_team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fs.Teams'),
        ),
    ]
