# Generated by Django 2.0.1 on 2018-02-11 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0025_auto_20180211_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='bar_role',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fs.Bar_Role'),
        ),
    ]
