# Generated by Django 2.0.1 on 2018-03-24 21:59

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0025_auto_20180324_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_num',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
    ]
