# Generated by Django 2.0.1 on 2018-02-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0026_events_bar_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='events',
            name='event_time',
            field=models.TimeField(default=None),
        ),
    ]
