# Generated by Django 2.0.1 on 2018-04-06 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0026_auto_20180324_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattendance',
            name='fan_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fs.FanGroup'),
        ),
    ]
