# Generated by Django 2.0.1 on 2018-04-06 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0028_auto_20180406_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventattendance',
            name='fan_group',
        ),
    ]
