# Generated by Django 2.0.1 on 2018-02-13 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0028_event_attendence_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_bar',
            name='ncaabb_affiliation',
            field=models.ForeignKey(default=None, limit_choices_to={'team_league': 8}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fs.Teams'),
        ),
        migrations.AddField(
            model_name='user_bar',
            name='ncaafb_affiliation',
            field=models.ForeignKey(default=None, limit_choices_to={'team_league': 7}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fs.Teams'),
        ),
        migrations.AddField(
            model_name='user_fan',
            name='fav_ncaabb',
            field=models.ForeignKey(default=None, limit_choices_to={'team_league': 8}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fs.Teams'),
        ),
        migrations.AddField(
            model_name='user_fan',
            name='fav_ncaafb',
            field=models.ForeignKey(default=None, limit_choices_to={'team_league': 7}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fs.Teams'),
        ),
    ]
