# Generated by Django 2.0.1 on 2018-02-16 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0029_auto_20180213_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password_hash', models.CharField(default=None, max_length=128)),
                ('name', models.CharField(max_length=70)),
                ('user_location', models.CharField(max_length=32)),
                ('street_address', models.CharField(max_length=95)),
                ('city', models.CharField(max_length=35)),
                ('state', models.CharField(max_length=20)),
                ('zip_code', models.CharField(max_length=5)),
                ('phone_num', models.PositiveIntegerField(default=None)),
                ('member_since', models.DateTimeField(auto_now_add=True)),
                ('fav_epl', models.ForeignKey(default=None, limit_choices_to={'team_league': 5}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fs.Teams')),
                ('fav_mlb', models.ForeignKey(default=None, limit_choices_to={'team_league': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fs.Teams')),
                ('fav_mls', models.ForeignKey(default=None, limit_choices_to={'team_league': 6}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fs.Teams')),
                ('fav_nba', models.ForeignKey(default=None, limit_choices_to={'team_league': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fs.Teams')),
                ('fav_ncaabb', models.ForeignKey(default=None, limit_choices_to={'team_league': 8}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fs.Teams')),
                ('fav_ncaafb', models.ForeignKey(default=None, limit_choices_to={'team_league': 7}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fs.Teams')),
                ('fav_nfl', models.ForeignKey(default=None, limit_choices_to={'team_league': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fs.Teams')),
                ('fav_nhl', models.ForeignKey(default=None, limit_choices_to={'team_league': 4}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fs.Teams')),
            ],
        ),
    ]
