# Generated by Django 2.0.1 on 2018-02-16 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0031_auto_20180216_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_bar',
            name='epl_affiliation',
        ),
        migrations.RemoveField(
            model_name='user_bar',
            name='mlb_affiliation',
        ),
        migrations.RemoveField(
            model_name='user_bar',
            name='mls_affiliation',
        ),
        migrations.RemoveField(
            model_name='user_bar',
            name='nba_affiliation',
        ),
        migrations.RemoveField(
            model_name='user_bar',
            name='ncaabb_affiliation',
        ),
        migrations.RemoveField(
            model_name='user_bar',
            name='ncaafb_affiliation',
        ),
        migrations.RemoveField(
            model_name='user_bar',
            name='nfl_affiliation',
        ),
        migrations.RemoveField(
            model_name='user_bar',
            name='nhl_affiliation',
        ),
        migrations.RemoveField(
            model_name='user_fan',
            name='fav_epl',
        ),
        migrations.RemoveField(
            model_name='user_fan',
            name='fav_mlb',
        ),
        migrations.RemoveField(
            model_name='user_fan',
            name='fav_mls',
        ),
        migrations.RemoveField(
            model_name='user_fan',
            name='fav_nba',
        ),
        migrations.RemoveField(
            model_name='user_fan',
            name='fav_ncaabb',
        ),
        migrations.RemoveField(
            model_name='user_fan',
            name='fav_ncaafb',
        ),
        migrations.RemoveField(
            model_name='user_fan',
            name='fav_nfl',
        ),
        migrations.RemoveField(
            model_name='user_fan',
            name='fav_nhl',
        ),
        migrations.DeleteModel(
            name='User_Bar',
        ),
        migrations.DeleteModel(
            name='User_Fan',
        ),
    ]
