# Generated by Django 2.0.1 on 2018-02-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0033_auto_20180216_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite_Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_team', models.ManyToManyField(to='fs.Teams')),
                ('user_id', models.ManyToManyField(to='fs.User')),
            ],
        ),
    ]
