# Generated by Django 2.0.1 on 2018-02-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0035_auto_20180216_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_attendence',
            name='user_role',
        ),
        migrations.AddField(
            model_name='event_attendence',
            name='creator',
            field=models.BooleanField(default=0),
        ),
        migrations.DeleteModel(
            name='Attendee_Role',
        ),
    ]
