# Generated by Django 2.0.1 on 2018-02-17 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0037_user_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_attendence',
            name='creator',
        ),
        migrations.AddField(
            model_name='events',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fs.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='events',
            name='bar',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bar', to='fs.User'),
        ),
    ]
