# Generated by Django 2.0.1 on 2018-02-17 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0038_auto_20180217_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='bar_role',
        ),
        migrations.DeleteModel(
            name='Bar_Role',
        ),
    ]
